In [2]:
#파일 저장
import numpy as np

data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)  #저장
data = []                      #데이터 삭제
print(data)
data = np.load('datafile.npy') #로드
print(data)

[ 0.06358965  1.07283721  0.05204627 -0.36729331  0.22264153]
[]
[ 0.06358965  1.07283721  0.05204627 -0.36729331  0.22264153]


In [4]:
#여러 ndarray형을 저장
import numpy as np

data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1 = data1, data2 = data2) #Save
data1 = [] #Data Delete
data2 = []
outfile = np.load('datafile2.npz') #load
print(outfile.files) #View Saved Data

data1 = outfile['data1'] #output data1
data2 = outfile['data2'] #output data2
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
