In [13]:
#배열 실습
x=[1,1,2,3,5]
print(x)
x[2]

print(type(x))
print(type(x[0]))

[1, 1, 2, 3, 5]
<class 'list'>
<class 'int'>


In [12]:
#range 실습
y = range(5, 10)
for i in y:
    print(i)
    
print(y)

z = list(range(5, 10))
print(z)

5
6
7
8
9
range(5, 10)
[5, 6, 7, 8, 9]


In [19]:
#tuple실습
a=(1, 2, 3)
print(a)

print(a[1])

type(a)

#tuple형은 요소 수정을 할 수 없음
#a[1] = 4
#print(a[1])

(1, 2, 3)
2


TypeError: 'tuple' object does not support item assignment

In [25]:
#if문의 사용
x = 11
if x > 10:
    print('x is ')#...(A1)
    print('      larger than 10.')#...(A2)
else:
    print('x is smaller than 11')#...(B1)
    
x > 10

type(x>10)

x = 15
if 10<=x and x<=20:
    print('x is between 10 and 20')

x is 
      larger than 10.
x is between 10 and 20


In [27]:
#for문의 사용
for i in [1, 2, 3]:
    print(i)
    
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i]=num[i]*2
    
print(num)

1
2
3
[4, 8, 12, 16, 20]


In [28]:
#enumerate의 사용
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n * 2
    
print(num)

[4, 8, 12, 16, 20]


In [41]:
#numpy의 사용
import numpy as np

x = np.array([1, 2, 3])
print(x)
y = np.array([4, 5, 6])
print(x+y)

print(type(x))

print(x[0])

x[0] = 100
print(x)

print(np.arange(10))

#numpy사용시 주의 사항
a = np.array([1, 1])
b = a#이렇게 복사할 시 a의 주소가 b에 들어가게 되어 b를 수정하게 되면 a가 같이 수정 되어 버린다.
print('a=' + str(a))
print('b=' + str(b))
b[0] = 100
print('a=' + str(a))
print('b=' + str(b))

a = np.array([1, 1])
b = a.copy()#값을 복사하기 위해서는 copy()를 사용한다.
print('a=' + str(a))
print('b=' + str(b))
b[0] = 100
print('a=' + str(a))
print('b=' + str(b))

[1 2 3]
[5 7 9]
<class 'numpy.ndarray'>
1
[100   2   3]
[0 1 2 3 4 5 6 7 8 9]
a=[1 1]
b=[1 1]
a=[100   1]
b=[100   1]
a=[1 1]
b=[1 1]
a=[1 1]
b=[100   1]


In [88]:
#행렬
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

x.shape#행렬의 크기를 리턴 형은 tuple형

w, h = x.shape
print(w)
print(h)

print(x[1, 2])

x[1, 2] = 100
print(x)

print(np.ones((2,10)))

print(np.random.rand(2, 3))#난수 행렬
print(np.random.randn(2, 3))#난수 행렬(가우스함수)

print(np.random.randint(1, 10, (2, 3)))#범위 난수

a = np.arange(10)
print(a)

print(a.reshape(2, 5))#전체 사이즈는 최초 생성때 사이즈를 맞춰야 함 안그럼 오류 발생

#행렬 각 요소의 사칙연산
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

#스칼라 곱셈
print(10*x)

#산술 함수
x = np.array([[4, 4, 4], [8, 8, 8]])
print(np.exp(x))

#행렬 곱
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1] ,[2, 2], [3, 3]])
print(v.dot(w))

[[1 2 3]
 [4 5 6]]
2
3
6
[[  1   2   3]
 [  4   5 100]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.44135092 0.49300247 0.80592219]
 [0.34744394 0.88956569 0.20615769]]
[[ 0.78372297  0.27569301  0.66684438]
 [-1.00923007  2.08499014 -0.22016167]]
[[9 7 7]
 [7 6 7]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 5  5  5]
 [10 10 10]]
[[40 40 40]
 [80 80 80]]
[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]
[[14 14]
 [32 32]]


In [8]:
#슬라이싱
import numpy as np

x = np.arange(10)
print(x)
print(x[:5])
print(x[5:])
print(x[3:8])
print(x[3:8:2])
print(x[::-1])

#슬라이스는 1차원 이상 배열에서도 사용 가능
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 0:2])#0~1번째배열까지 0~1까지 요소들 표시

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5 6 7]
[3 5 7]
[9 8 7 6 5 4 3 2 1 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [12]:
#조건을 만족하는 데이터의 수정
import numpy as np

x = np.array([1, 1, 2, 3, 5, 8, 13])
print(x>3)
print(x[x>3])
x[x>3] = 999
print(x)

[False False False False  True  True  True]
[ 5  8 13]
[  1   1   2   3 999 999 999]


In [13]:
#Help사용 함수의 사용 방법을 표시해 준다.
import numpy as np
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [15]:
#함수 정의
def my_func1():
    print('Hi!')
    #함수의 내용을 들여쓰기까지만 
my_func1()#함수 실행

def my_func2(a, b):
    c = a + b
    print(c)
my_func2(1, 2)

Hi!
3
