In [18]:
#리스트 4-3-(1) 행렬
import numpy as np

a = np.array([[1, 2, 3,], [4, 5, 6]])
print(a)

#리스트 4-3-(2)행렬 합, 차
b = np.array([[7, 8, 9], [10, 11, 12]])

print(a+b)
print(a-b)

#리스트 4-3-(3) 스칼라 곱
A = np.array([[1, 2, 3,], [4, 5, 6]])
print(2*A)

#리스트 4-3-(4) 행렬 곱 (백터의 내적 계산과 동일)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A.dot(B))

#리스트 4-3-(5) 일반적인 *, /을 사용할 경우 각 행렬의 요소를 곱셈,나눗셈을 수행한다.
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A*B)
print(A/B)

#리스트 4-3-(6) 2X3, 3X2 행렬 곱셈 계산
A = np.array([[1, 2, 3], [-1, -2, -3]])
B = np.array([[4, -4], [5, -5], [6, -6]])
print(A.dot(B))

#리스트 4-3-(7) 단위 행렬
print(np.identity(3))
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A.dot(np.identity(3)))

#리스트 4-3-(8) 역행렬
A = np.array([[1, 2], [3, 4]])
invA = np.linalg.inv(A)
print(invA)
print(A.dot(invA))

[[1 2 3]
 [4 5 6]]
[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 2  4  6]
 [ 8 10 12]]
32
[ 4 10 18]
[0.25 0.4  0.5 ]
[[ 32 -32]
 [-32  32]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
